### ISSUE TITLE
Build Failure from missing boost include during CxxGrammarMetaProgram make

### ISSUE THREAD

**Issue by ian-bertolacci** [rose-compiler/rose#2]
Deep into the build when creating the CxxGrammarMetaProgram executable the build fails.
I am given the error:

```
ld: warning: libboost_chrono.so.1.53.0, needed by path/to/boost/lib/libboost_wave.so, not found
```

There seems to be a partial, hand fix to build CxxGrammarMetaProgram:

I dived into $ROSE/build_tree/src/ROSETTA/src where this was being compiled, then copied the command that make tried to execute to build CxxGrammarMetaProgram:

```
g++ -g -O2 -Wall -o CxxGrammarMetaProgram CxxGrammarMetaProgram.o grammar.o grammarString.o terminal.o type.o symbol.o expression.o statement.o support.o binaryInstruction.o storageSize.o visitorSupport.o poolBasedTraversal.o node.o buildAstFileIO.o buildStorageClasses.o buildConstructorsWithoutSourcePositionInformation.o outputClassesAndFields.o buildAtermSupport.o terminals.o  -L/users/ibertolacc/rose/build-dir/fake_boost/lib -lboost_date_time -lboost_filesystem -lboost_program_options -lboost_regex -lboost_system -lboost_wave -lrt -ldl ../../../src/util/.libs/libroseutil.a
```

Here I notices that it was missing:

```
-lboost_chrono
```

So I added it in, ran it, which gave me the error:

```
ld: warning: libboost_thread.so.1.53.0, needed by /path/to/boost/lib/libboost_wave.so, not found
```

so I added:

```
-lboost_thread
```

giving a complete command:

```
g++ -g -O2 -Wall -o CxxGrammarMetaProgram CxxGrammarMetaProgram.o grammar.o grammarString.o terminal.o type.o symbol.o expression.o statement.o support.o binaryInstruction.o storageSize.o visitorSupport.o poolBasedTraversal.o node.o buildAstFileIO.o buildStorageClasses.o buildConstructorsWithoutSourcePositionInformation.o outputClassesAndFields.o buildAtermSupport.o terminals.o  -L/users/ibertolacc/rose/build-dir/fake_boost/lib -lboost_date_time -lboost_filesystem -lboost_program_options -lboost_regex -lboost_system -lboost_wave -lrt -ldl -lboost_chrono -lboost_thread ../../../src/util/.libs/libroseutil.a
```

Running this builds CxxGrammarMetaProgram.
Ensuring that your LD_LIBRARY_PATH includes the path to the boost libs

``` bash
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/boost/lib
export LD_LIBRARY_PATH
```

then going back up to the original build directory ( $ROSE/build_tree )
and executing make again will continue the make process from where it stopped.
However I personally have not yet fully built yet, and I write this as I watch the rest of it compile.

**Comment by leek2** [comment]
Sorry we've been unresponsive to this.  We're trying to improve.  
I'm pretty sure this issue was fixed a long time ago.  Do you still have (or care about) this issue?  

If you don't respond by 9/20 I'll assume it isn't an issue anymore and close this.

**Comment by ian-bertolacci** [comment]
We can close it. Right now I'm not even sure how I'd test it. If we realize that this is still an issue we can always re-open it.

Thanks! And glad to see some new life in this project!

**Comment by leek2** [comment]
Great.  We actually have been pretty active with our internal and customer development.  But we're trying to improve our engagement with the community.  Please let us know if you have any trouble.  We'll be more responsive next time.
